import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";

/**
 * GET /api/unsubscribe?token=<token>
 *
 * One-click unsubscribe. The token is stored in leads.unsubscribe_token
 * (auto-generated by Postgres DEFAULT gen_random_uuid()::text on insert).
 *
 * Sets leads.unsubscribed = true for the matching row.
 * Returns a plain HTML confirmation page — no redirect needed.
 */
export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get("token");

  if (!token) {
    return htmlResponse(
      "Invalid link",
      "This unsubscribe link is invalid or missing a token.",
      400
    );
  }

  const { data, error } = await supabaseAdmin
    .from("leads")
    .update({ unsubscribed: true })
    .eq("unsubscribe_token", token)
    .select("email")
    .single();

  if (error || !data) {
    return htmlResponse(
      "Link not found",
      "This unsubscribe link is invalid or has already been used.",
      404
    );
  }

  return htmlResponse(
    "Unsubscribed",
    `You've been unsubscribed from StackAudit pricing alerts. You won't receive any further emails at ${data.email}.`
  );
}

function htmlResponse(title: string, message: string, status = 200) {
  return new NextResponse(
    `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} — StackAudit</title>
  <style>
    body { font-family: system-ui, sans-serif; background: #0f172a; color: #e2e8f0;
           display: flex; align-items: center; justify-content: center;
           min-height: 100vh; margin: 0; }
    .card { background: #1e293b; border: 1px solid #334155; border-radius: 12px;
            padding: 40px 32px; max-width: 480px; text-align: center; }
    h1 { font-size: 22px; font-weight: 700; margin: 0 0 12px; }
    p  { color: #94a3b8; font-size: 15px; line-height: 1.6; margin: 0 0 24px; }
    a  { color: #4ade80; text-decoration: none; font-size: 14px; }
  </style>
</head>
<body>
  <div class="card">
    <h1>${title}</h1>
    <p>${message}</p>
    <a href="/">← Run a new audit</a>
  </div>
</body>
</html>`,
    { status, headers: { "Content-Type": "text/html" } }
  );
}
